// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyWeb.Data;

#nullable disable

namespace MoneyWeb.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20260218180802_CriandoBancoDeDados")]
    partial class CriandoBancoDeDados
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MoneyWeb.Models.Entities.Cartao", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("ContaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateOnly>("DataFechamento")
                        .HasColumnType("date")
                        .HasColumnName("DATA_FECHAMENTO");

                    b.Property<DateOnly>("DataVencimento")
                        .HasColumnType("date")
                        .HasColumnName("DATA_VENCIMENTO");

                    b.Property<decimal>("Limite")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("LIMITE");

                    b.Property<decimal>("LimiteDisponivel")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("LIMITE_DISPONIVEL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("ValorParcelado")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("VALOR_PARCELADO");

                    b.HasKey("Id");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("idx_fk_cartao_conta");

                    b.ToTable("cartao", (string)null);
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Categoria", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("COR")
                        .IsFixedLength();

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("NOME");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("TIPO")
                        .IsFixedLength();

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_fk_categoria_usuario");

                    b.ToTable("categoria", (string)null);
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Conta", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Saldo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("SALDO")
                        .HasDefaultValueSql("0.00");

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("USUARIO_ID");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_fk_conta_usuario");

                    b.ToTable("conta", (string)null);
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Lancamento", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint?>("CartaoId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("CARTAO_ID");

                    b.Property<uint>("CategoriaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("CATEGORIA_ID");

                    b.Property<uint>("ContaId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("CONTA_ID");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("DATA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("DESCRICAO");

                    b.Property<bool>("Fixo")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("FIXO");

                    b.Property<string>("Observacao")
                        .HasColumnType("varchar(1000)")
                        .HasColumnName("OBSERVACAO");

                    b.Property<bool>("PreLancamento")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("PRE_LANCAMENTO");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("char(7)")
                        .HasColumnName("TIPO")
                        .IsFixedLength();

                    b.Property<uint>("UsuarioId")
                        .HasColumnType("int unsigned")
                        .HasColumnName("USUARIO_ID");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(9,2)")
                        .HasColumnName("VALOR");

                    b.HasKey("Id");

                    b.HasIndex("CartaoId")
                        .HasDatabaseName("idx_fk_lancamento_cartao");

                    b.HasIndex("CategoriaId")
                        .HasDatabaseName("idx_fk_lancamento_categoria");

                    b.HasIndex("ContaId")
                        .HasDatabaseName("idx_fk_lancamento_conta");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("idx_fk_lancamento_usuario");

                    b.ToTable("lancamento", (string)null);
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Usuario", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned")
                        .HasColumnName("ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("USUARIO");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("char(60)")
                        .HasColumnName("SENHA")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("NomeUsuario")
                        .IsUnique()
                        .HasDatabaseName("usuario_unique");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Cartao", b =>
                {
                    b.HasOne("MoneyWeb.Models.Entities.Conta", "Conta")
                        .WithMany("Cartoes")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cartao_conta");

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Categoria", b =>
                {
                    b.HasOne("MoneyWeb.Models.Entities.Usuario", "Usuario")
                        .WithMany("Categorias")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_categoria_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Conta", b =>
                {
                    b.HasOne("MoneyWeb.Models.Entities.Usuario", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conta_usuario");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Lancamento", b =>
                {
                    b.HasOne("MoneyWeb.Models.Entities.Cartao", "Cartao")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CartaoId")
                        .HasConstraintName("fk_lancamento_cartao");

                    b.HasOne("MoneyWeb.Models.Entities.Categoria", "Categoria")
                        .WithMany("Lancamentos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lancamento_categoria");

                    b.HasOne("MoneyWeb.Models.Entities.Conta", "Conta")
                        .WithMany("Lancamentos")
                        .HasForeignKey("ContaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lancamento_conta");

                    b.HasOne("MoneyWeb.Models.Entities.Usuario", "Usuario")
                        .WithMany("Lancamentos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lancamento_usuario");

                    b.Navigation("Cartao");

                    b.Navigation("Categoria");

                    b.Navigation("Conta");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Cartao", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Categoria", b =>
                {
                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Conta", b =>
                {
                    b.Navigation("Cartoes");

                    b.Navigation("Lancamentos");
                });

            modelBuilder.Entity("MoneyWeb.Models.Entities.Usuario", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Contas");

                    b.Navigation("Lancamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
